import crypto from 'node:crypto';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!supabaseUrl || !serviceRoleKey) throw new Error('Missing server-side Supabase configuration');
export const supabaseAdmin = createClient(supabaseUrl, serviceRoleKey);

export const SCOPES = ['profile:read','passport:read','connect:read','connect:write','ai:use','call:read','call:write','companies:read','companies:write','properties:read','properties:write','world:read','world:write','investors:read','credits:read','verification:read','webhooks:manage','oauth:manage'];
const SCOPE_SET = new Set(SCOPES);

export function cors(res){res.setHeader('Access-Control-Allow-Origin',process.env.MERVEIL_API_CORS_ORIGIN||'*');res.setHeader('Access-Control-Allow-Headers','authorization, content-type, x-api-key, x-request-id');res.setHeader('Access-Control-Allow-Methods','GET, POST, PATCH, DELETE, OPTIONS');res.setHeader('Access-Control-Expose-Headers','X-Request-Id, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, Retry-After');}
export function requestId(req,res){const supplied=String(req.headers['x-request-id']||'').trim();const id=supplied&&/^[A-Za-z0-9._:-]{8,100}$/.test(supplied)?supplied:crypto.randomUUID();res?.setHeader('X-Request-Id',id);req._merveilRequestId=id;return id;}
export function json(res,status,body,headers={}){cors(res);Object.entries(headers).forEach(([k,v])=>res.setHeader(k,String(v)));return res.status(status).json(body);}
export function bearer(req){const value=req.headers.authorization||'';return value.startsWith('Bearer ')?value.slice(7):null;}
export async function requireUser(req){const token=bearer(req);if(!token)return{error:'Missing Bearer token'};const {data,error}=await supabaseAdmin.auth.getUser(token);if(error||!data?.user)return{error:'Invalid or expired authentication token'};return{user:data.user};}
export function hashKey(key){return crypto.createHash('sha256').update(key).digest('hex');}
export function newApiKey(environment){const prefix=environment==='production'?'mv_live_':'mv_test_';const key=`${prefix}${crypto.randomBytes(32).toString('base64url')}`;return{key,prefix:key.slice(0,13),hash:hashKey(key)};}
export function newSecret(prefix='mv_secret_'){const value=`${prefix}${crypto.randomBytes(32).toString('base64url')}`;return{value,hash:hashKey(value)};}
export function apiKey(req){return req.headers['x-api-key']||(req.headers.authorization||'').replace(/^Bearer\s+/i,'')||null;}
function rateLimitFor(environment){const fallback=environment==='production'?120:30;const raw=Number(environment==='production'?process.env.MERVEIL_API_RATE_LIMIT:process.env.MERVEIL_API_SANDBOX_RATE_LIMIT);return Number.isFinite(raw)&&raw>=1&&raw<=10000?Math.floor(raw):fallback;}
export async function requireApiKey(req,requiredScope=null,res=null){const started=Date.now();const rid=requestId(req,res);const headers={'X-Request-Id':rid};const key=apiKey(req);if(!key)return{error:'Missing API key',status:401,requestId:rid,headers};if(String(key).length<20||String(key).length>200)return{error:'Invalid API key',status:401,requestId:rid,headers};const {data,error}=await supabaseAdmin.from('api_applications').select('id,user_id,name,environment,scopes,status').eq('key_hash',hashKey(String(key))).maybeSingle();if(error||!data||data.status!=='active')return{error:'Invalid or revoked API key',status:401,requestId:rid,headers};if(requiredScope&&!(data.scopes||[]).includes(requiredScope))return{error:`Missing required scope: ${requiredScope}`,status:403,requestId:rid,headers,app:data};const limit=rateLimitFor(data.environment);const bucket=new Date(Math.floor(Date.now()/60000)*60000).toISOString();const reset=Math.ceil((Date.parse(bucket)+60000)/1000);if(res){res.setHeader('X-RateLimit-Limit',String(limit));res.setHeader('X-RateLimit-Reset',String(reset));}const {data:allowed,error:rateError}=await supabaseAdmin.rpc('consume_api_rate_limit',{p_application_id:data.id,p_bucket_start:bucket,p_limit:limit});if(rateError)return{error:'Rate limiting service unavailable',status:503,requestId:rid,headers,app:data};if(allowed===false){const retryAfter=Math.max(1,reset-Math.floor(Date.now()/1000));const rateHeaders={...headers,'Retry-After':String(retryAfter),'X-RateLimit-Remaining':'0'};if(res)res.setHeader('X-RateLimit-Remaining','0');return{error:'Rate limit exceeded',status:429,requestId:rid,headers:rateHeaders,app:data};}if(res)res.setHeader('X-RateLimit-Remaining',String(Math.max(0,limit-1)));await supabaseAdmin.from('api_applications').update({last_used_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',data.id);return{app:data,requestId:rid,started,limit,headers};}
export function hasScope(app,scope){return !scope||(Array.isArray(app?.scopes)&&app.scopes.includes(scope));}
export function requireScope(app,scope){if(!hasScope(app,scope))return{error:`Missing required scope: ${scope}`};return null;}
export function sanitizeScopes(scopes){if(!Array.isArray(scopes))return['profile:read'];const clean=[...new Set(scopes.map(String).filter((scope)=>SCOPE_SET.has(scope)))];return clean.length?clean:['profile:read'];}
export async function logApiUsage(ctx,req,statusCode){if(!ctx?.app?.id)return;try{await supabaseAdmin.from('api_usage_logs').insert({application_id:ctx.app.id,user_id:ctx.app.user_id,method:req.method||'GET',path:req.url?.split('?')[0]||'/',status_code:statusCode,request_id:ctx.requestId||req._merveilRequestId||crypto.randomUUID(),latency_ms:Math.max(0,Date.now()-(ctx.started||Date.now()))});}catch(_){} }
export function safeProfile(row){if(!row)return null;return{id:row.id,name:row.name,bio:row.bio,avatar_url:row.avatar_url,country:row.country,city:row.city,profession:row.profession,skills:row.skills,languages:row.languages,website_url:row.website_url,portfolio_url:row.portfolio_url,account_type:row.account_type,company_name:row.company_name,passport_tier:row.passport_tier,kyc_level:row.kyc_level,kyc_status:row.kyc_status,created_at:row.created_at};}
