const commercialPanel=(()=>{
  let client=null, token=null, org=null;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  async function init(){try{const r=await fetch('/api/v1/developer/config');const j=await r.json();if(!r.ok)return;client=window.supabase?.createClient?window.supabase.createClient(j.data.supabase_url,j.data.supabase_publishable_key):null;}catch(_){} }
  async function load(){try{const r=await fetch('/api/v1/organization',{headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}});const j=await r.json();if(r.ok)org=j.data;draw();}catch(_){} }
  function draw(){const nav=document.querySelector('.nav');if(!nav||document.getElementById('commercialNav'))return;const b=document.createElement('button');b.id='commercialNav';b.textContent='Plan & Billing';b.onclick=()=>show();nav.appendChild(b);}
  async function show(){if(!token){try{const r=await fetch('/api/v1/developer/config');const j=await r.json();const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2.102.0');client=createClient(j.data.supabase_url,j.data.supabase_publishable_key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});token=(await client.auth.getSession()).data.session?.access_token;}catch(_){} }await load();if(!org)return;const d=org.subscription||{};const p=d.plan||{};const limits=p.requests_per_month?Number(p.requests_per_month).toLocaleString():'Unlimited';const used=Number(org.usage?.requests||0);const c=document.getElementById('content');if(!c)return;c.innerHTML=`<div class="section"><div class="row"><div><h2>${esc(org.organization.name)}</h2><p class="muted">${esc(org.role)} · Developer organization</p></div><span class="badge good">${esc(d.status||'active')}</span></div></div><div class="cards"><div class="card"><div class="muted">Current plan</div><div class="metric">${esc(p.name||'Sandbox')}</div><p class="muted">${p.monthly_price?`$${esc(p.monthly_price)}/month`:'Free'}</p></div><div class="card"><div class="muted">Monthly requests</div><div class="metric">${used.toLocaleString()} <span class="muted">/ ${limits}</span></div></div><div class="card"><div class="muted">AI units</div><div class="metric">${Number(org.usage?.ai||0).toLocaleString()}</div></div><div class="card"><div class="muted">Call minutes</div><div class="metric">${Number(org.usage?.call_minutes||0).toLocaleString()}</div></div></div><div class="section"><h2>Subscription</h2><p class="muted">${p.description?esc(p.description):'Your developer platform subscription controls production access and usage limits.'}</p><div class="actions"><button class="btn" id="refreshCommercial">Refresh usage</button></div></div><div class="section"><h2>Available plans</h2><div class="cards"><div class="card"><h3>Sandbox</h3><p class="muted">Free testing environment for development.</p></div><div class="card"><h3>Developer</h3><p class="muted">For individual products moving toward production.</p></div><div class="card"><h3>Growth</h3><p class="muted">Higher limits for growing integrations.</p></div><div class="card"><h3>Business</h3><p class="muted">Production workloads and larger teams.</p></div><div class="card"><h3>Enterprise</h3><p class="muted">Custom limits, security and commercial terms.</p></div></div><p class="muted" style="margin-top:12px">Plan changes and payment collection will be connected to Merveil's existing payment infrastructure before public billing launch.</p></div>`;document.getElementById('refreshCommercial').onclick=load;}
  function observe(){new MutationObserver(()=>draw()).observe(document.getElementById('app'),{childList:true,subtree:true});}
  return{start:async()=>{observe();await init();setInterval(async()=>{try{const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2.102.0');const r=await fetch('/api/v1/developer/config');const j=await r.json();client=createClient(j.data.supabase_url,j.data.supabase_publishable_key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});token=(await client.auth.getSession()).data.session?.access_token;if(token)draw();}catch(_){ }},5000);}};
})();
commercialPanel.start();