import { json, requireUser, newSecret, hashKey, supabaseAdmin } from './_lib.js';
const events=['connection.created','connection.updated','message.created','verification.updated','passport.updated','company.updated','property.updated','world.post.created','investor.updated','call.completed','ai.completed'];
const body=req=>{try{return typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});}catch{return{};}};
export default async function handler(req,res){
 if(req.method==='OPTIONS')return json(res,204,null);
 const auth=await requireUser(req);if(auth.error)return json(res,401,{error:'unauthorized',message:auth.error});
 const appId=String(req.query?.app_id||'');if(!appId)return json(res,400,{error:'app_id_required'});
 const {data:app}=await supabaseAdmin.from('api_applications').select('id').eq('id',appId).eq('user_id',auth.user.id).maybeSingle();if(!app)return json(res,404,{error:'application_not_found'});
 if(req.method==='GET'){const {data,error}=await supabaseAdmin.from('api_webhooks').select('id,url,events,status,created_at,updated_at,failure_count,last_delivery_at,last_success_at,last_failure_at').eq('application_id',appId).order('created_at',{ascending:false});if(error)return json(res,500,{error:'database_error'});return json(res,200,{data,available_events:events});}
 if(req.method==='POST'){const b=body(req);if(!/^https:\/\//i.test(String(b.url||'')))return json(res,400,{error:'https_url_required'});const selected=[...new Set((Array.isArray(b.events)?b.events:[]).map(String).filter(e=>events.includes(e)))];if(!selected.length)return json(res,400,{error:'events_required',available_events:events});const secret=newSecret('mwhsec_');const {data,error}=await supabaseAdmin.from('api_webhooks').insert({application_id:appId,url:String(b.url),events:selected,secret_hash:hashKey(secret.value),status:'active'}).select('id,url,events,status,created_at').single();if(error)return json(res,500,{error:'database_error'});return json(res,201,{data,signing_secret:secret.value,warning:'Store this signing secret securely. It is shown once.'});}
 if(req.method==='PATCH'){const id=String(req.query?.id||'');if(!id)return json(res,400,{error:'webhook_id_required'});const b=body(req),patch={updated_at:new Date().toISOString()};if(['active','paused','revoked'].includes(b.status))patch.status=b.status;if(Array.isArray(b.events)){const selected=[...new Set(b.events.map(String).filter(e=>events.includes(e)))];if(!selected.length)return json(res,400,{error:'events_required',available_events:events});patch.events=selected;}if(typeof b.url==='string'){if(!/^https:\/\//i.test(b.url))return json(res,400,{error:'https_url_required'});patch.url=b.url;}const {data,error}=await supabaseAdmin.from('api_webhooks').update(patch).eq('id',id).eq('application_id',appId).select('id,url,events,status,updated_at').maybeSingle();if(error||!data)return json(res,404,{error:'webhook_not_found'});return json(res,200,{data});}
 return json(res,405,{error:'method_not_allowed'});
}
