import { supabaseAdmin, json, requestId, requireUser } from '../_lib.js';

const readBody=req=>{try{return typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});}catch{return{};}};
const own=async(projectId,userId)=>{const {data,error}=await supabaseAdmin.from('developer_projects').select('id,name,slug,twin,meta').eq('id',projectId).eq('owner_user_id',userId).maybeSingle();if(error)throw error;return data;};
const files=async(projectId,userId)=>{const {data,error}=await supabaseAdmin.from('developer_project_files').select('path,content').eq('project_id',projectId).eq('owner_user_id',userId).order('path');if(error)throw error;return data||[];};
function validate(project,fs){const runtime=project.twin?.runtime||'static';const errors=[],warnings=[];const paths=new Set(fs.map(f=>f.path));
 if(!fs.length)errors.push('Project has no files.');
 if(runtime==='static'&&!paths.has('index.html'))errors.push('Static project requires index.html.');
 if(['node','nextjs'].includes(runtime)){if(!paths.has('package.json'))errors.push(`${runtime} project requires package.json.`);else{const f=fs.find(x=>x.path==='package.json');try{const p=JSON.parse(f.content);if(!p.scripts?.build)warnings.push('package.json has no build script; provider build may not run.');}catch{errors.push('package.json is not valid JSON.');}}}
 for(const f of fs){if(f.path.includes('..'))errors.push(`Unsafe path: ${f.path}`);if(f.content.length>2_000_000)errors.push(`File too large: ${f.path}`);}
 if(runtime==='static'&&paths.has('index.html')){const html=fs.find(x=>x.path==='index.html').content;if(!/<html[\s>]/i.test(html))warnings.push('index.html has no <html> element.');if(!/<meta[^>]+viewport/i.test(html))warnings.push('Mobile viewport meta tag is missing.');}
 return {runtime,errors,warnings,passed:errors.length===0};}
async function recordBuild(project,userId,result,kind='build'){const {data,error}=await supabaseAdmin.from('developer_builds').insert({project_id:project.id,owner_user_id:userId,status:result.passed?'success':'failed',logs:JSON.stringify({kind,runtime:result.runtime,errors:result.errors,warnings:result.warnings,files:result.file_count}),finished_at:new Date().toISOString()}).select('*').single();if(error)throw error;await supabaseAdmin.from('developer_projects').update({stage:result.passed?'built':'build_failed',status_label:result.passed?'Build passed':'Build failed',momentum:result.passed?100:Math.max(0,project.momentum||0),updated_at:new Date().toISOString()}).eq('id',project.id).eq('owner_user_id',userId);return data;}
export default async function handler(req,res){requestId(req,res);if(req.method==='OPTIONS')return json(res,204,{});const auth=await requireUser(req);if(!auth.user)return json(res,401,{error:'authentication_required'});const projectId=String(req.query?.project_id||'').trim();if(!projectId)return json(res,400,{error:'project_id_required'});try{const project=await own(projectId,auth.user.id);if(!project)return json(res,404,{error:'project_not_found'});const fs=await files(projectId,auth.user.id);const result={...validate(project,fs),file_count:fs.length};if(req.method==='POST'&&String(req.query?.action||'build')==='test'){result.kind='test';result.tests=result.passed?[{name:'project-structure',status:'passed'},{name:'runtime-contract',status:'passed'}]:[{name:'project-structure',status:'failed',errors:result.errors}];}else if(req.method!=='POST')return json(res,405,{error:'method_not_allowed'});const build=await recordBuild(project,auth.user.id,result,result.kind||'build');return json(res,result.passed?200:422,{ok:result.passed,build,result});}catch(error){console.error('[developer-build-engine]',error);return json(res,500,{error:'build_engine_failed'});}}
