import crypto from 'node:crypto';
import { supabaseAdmin, json, requestId, requireUser } from '../_lib.js';

async function resolveUser(req){
  const auth=await requireUser(req); if(auth.user)return auth.user;
  const cookie=String(req.headers.cookie||''); if(!cookie)return null;
  try{const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0];const host=String(req.headers.host||'').split(',')[0];const r=await fetch(`${proto}://${host}/api/auth-session?reason=developer`,{headers:{cookie},cache:'no-store'});const b=await r.json().catch(()=>null);return r.ok&&b?.authenticated&&b?.user?.id?b.user:null;}catch{return null;}
}
const body=req=>{try{return typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});}catch{return{};}};
const nameOk=v=>typeof v==='string'&&v.trim().length>=1&&v.trim().length<=80;
const slug=v=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'project';
const b64url=b=>Buffer.from(b).toString('base64url');
const random=n=>b64url(crypto.randomBytes(n));
const sha256=v=>crypto.createHash('sha256').update(v).digest('base64url');
const stateHash=v=>crypto.createHash('sha256').update(v).digest('hex');
function encryptionKey(){const raw=process.env.DEVELOPER_PROVIDER_ENCRYPTION_KEY||'';if(!raw)throw new Error('provider_encryption_key_not_configured');try{const k=/^[0-9a-f]{64}$/i.test(raw)?Buffer.from(raw,'hex'):Buffer.from(raw,'base64');if(k.length!==32)throw 0;return k;}catch{throw new Error('provider_encryption_key_invalid');}}
function seal(value){if(!value)return null;const iv=crypto.randomBytes(12),key=encryptionKey(),c=crypto.createCipheriv('aes-256-gcm',key,iv);const out=Buffer.concat([c.update(String(value),'utf8'),c.final()]);return [iv.toString('base64url'),c.getAuthTag().toString('base64url'),out.toString('base64url')].join('.');}
function openSealed(value){if(!value)return null;const [iv,tag,data]=String(value).split('.');const d=crypto.createDecipheriv('aes-256-gcm',encryptionKey(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString('utf8');}
function baseUrl(req){const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0];const host=String(req.headers.host||'').split(',')[0];return `${proto}://${host}`;}
function providerConfig(provider){
  if(provider==='github')return {clientId:process.env.GITHUB_DEVELOPER_CLIENT_ID,clientSecret:process.env.GITHUB_DEVELOPER_CLIENT_SECRET,authorize:'https://github.com/login/oauth/authorize',token:'https://github.com/login/oauth/access_token',scopes:['repo','read:user','user:email']};
  if(provider==='vercel')return {clientId:process.env.VERCEL_DEVELOPER_CLIENT_ID,clientSecret:process.env.VERCEL_DEVELOPER_CLIENT_SECRET,authorize:'https://vercel.com/oauth/authorize',token:'https://api.vercel.com/v2/oauth/access_token',scopes:['openid','email','profile','offline_access']};
  return null;
}
async function ownedProject(projectId,userId){const {data,error}=await supabaseAdmin.from('developer_projects').select('id,name,slug,owner_user_id').eq('id',projectId).eq('owner_user_id',userId).maybeSingle();return error||!data?null:data;}
async function providerConnection(projectId,userId,provider){const {data}=await supabaseAdmin.from('developer_provider_connections').select('*').eq('project_id',projectId).eq('owner_user_id',userId).eq('provider',provider).maybeSingle();return data||null;}

async function startOAuth(req,res,user,provider,projectId){
  const p=providerConfig(provider);if(!p?.clientId||!p?.clientSecret)return json(res,503,{error:`${provider}_oauth_not_configured`});
  const project=await ownedProject(projectId,user.id);if(!project)return json(res,404,{error:'project_not_found'});
  const state=random(32),verifier=random(48),redirectUri=`${baseUrl(req)}/api/v1/developer/projects?route=oauth_callback&provider=${provider}`;
  const {error}=await supabaseAdmin.from('developer_provider_oauth_states').insert({state_hash:stateHash(state),project_id:projectId,owner_user_id:user.id,provider,code_verifier:verifier,redirect_uri:redirectUri,expires_at:new Date(Date.now()+10*60*1000).toISOString()});
  if(error)return json(res,500,{error:'oauth_state_store_failed'});
  const q=new URLSearchParams({client_id:p.clientId,redirect_uri:redirectUri,state,response_type:'code'});
  q.set('scope',p.scopes.join(' '));q.set('code_challenge',sha256(verifier));q.set('code_challenge_method','S256');
  if(provider==='github')q.set('allow_signup','false');
  return res.redirect(302,`${p.authorize}?${q.toString()}`);
}
async function oauthCallback(req,res,provider){
  const state=String(req.query?.state||''),code=String(req.query?.code||''),error=String(req.query?.error||'');
  if(error)return res.redirect(302,`/developer/?provider=${provider}&oauth=error&reason=${encodeURIComponent(error)}`);
  if(!state||!code)return res.status(400).send('OAuth callback is missing state or code.');
  const {data:s}=await supabaseAdmin.from('developer_provider_oauth_states').select('*').eq('state_hash',stateHash(state)).is('consumed_at',null).gt('expires_at',new Date().toISOString()).maybeSingle();
  if(!s||s.provider!==provider)return res.status(400).send('Invalid or expired OAuth state.');
  const p=providerConfig(provider);if(!p?.clientId||!p?.clientSecret)return res.status(503).send('OAuth provider is not configured.');
  const params=new URLSearchParams({client_id:p.clientId,client_secret:p.clientSecret,code,redirect_uri:s.redirect_uri,code_verifier:s.code_verifier,grant_type:'authorization_code'});
  const tr=await fetch(p.token,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'},body:params});
  const tb=await tr.json().catch(()=>({}));if(!tr.ok||!tb.access_token)return res.status(502).send('Provider token exchange failed.');
  let externalId=null,externalName=null,scopes=String(tb.scope||'').split(/[,\s]+/).filter(Boolean),meta={};
  if(provider==='github'){
    const ur=await fetch('https://api.github.com/user',{headers:{Authorization:`Bearer ${tb.access_token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});const ub=await ur.json().catch(()=>({}));if(!ur.ok||!ub.id)return res.status(502).send('GitHub identity verification failed.');externalId=String(ub.id);externalName=ub.login;meta.avatar_url=ub.avatar_url||null;
  } else {
    const ur=await fetch('https://api.vercel.com/login/oauth/userinfo',{headers:{Authorization:`Bearer ${tb.access_token}`,Accept:'application/json'}});const ub=await ur.json().catch(()=>({}));if(!ur.ok||!ub.sub)return res.status(502).send('Vercel identity verification failed.');externalId=String(ub.sub);externalName=ub.preferred_username||ub.name||ub.email||'Vercel account';meta.email=ub.email||null;
  }
  const tokenExpiry=tb.expires_in?new Date(Date.now()+Number(tb.expires_in)*1000).toISOString():null;
  const {error:upsertError}=await supabaseAdmin.from('developer_provider_connections').upsert({project_id:s.project_id,owner_user_id:s.owner_user_id,provider,external_account_id:externalId,external_account_name:externalName,access_token_ciphertext:seal(tb.access_token),refresh_token_ciphertext:seal(tb.refresh_token||null),token_expires_at:tokenExpiry,scopes,status:'connected',metadata:meta,updated_at:new Date().toISOString()},{onConflict:'project_id,provider'});
  await supabaseAdmin.from('developer_provider_oauth_states').update({consumed_at:new Date().toISOString()}).eq('id',s.id);
  if(upsertError)return res.status(500).send('Provider connection could not be saved.');
  return res.redirect(302,`/developer/?project_id=${encodeURIComponent(s.project_id)}&provider=${provider}&oauth=connected`);
}
async function providerData(req,res,user,action,projectId){
  if(!projectId)return json(res,400,{error:'project_id_required'});const project=await ownedProject(projectId,user.id);if(!project)return json(res,404,{error:'project_not_found'});
  if(action==='provider_status'&&req.method==='GET'){const {data}=await supabaseAdmin.from('developer_provider_connections').select('provider,external_account_id,external_account_name,scopes,status,metadata,created_at,updated_at').eq('project_id',projectId).eq('owner_user_id',user.id);return json(res,200,{connections:data||[]});}
  if(action==='connect'&&req.method==='GET'){const provider=String(req.query?.provider||'').toLowerCase();if(!['github','vercel'].includes(provider))return json(res,400,{error:'unsupported_provider'});return startOAuth(req,res,user,provider,projectId);}
  if(action==='disconnect'&&req.method==='POST'){const provider=String(body(req).provider||'').toLowerCase();if(!['github','vercel'].includes(provider))return json(res,400,{error:'unsupported_provider'});await supabaseAdmin.from('developer_provider_connections').delete().eq('project_id',projectId).eq('owner_user_id',user.id).eq('provider',provider);return json(res,200,{disconnected:true,provider});}
  if(action==='github_repositories'&&req.method==='GET'){const c=await providerConnection(projectId,user.id,'github');if(!c)return json(res,409,{error:'github_not_connected'});const token=openSealed(c.access_token_ciphertext);const r=await fetch('https://api.github.com/user/repos?per_page=100&sort=updated',{headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});const b=await r.json().catch(()=>({}));if(!r.ok)return json(res,502,{error:'github_repositories_failed',details:b});return json(res,200,{repositories:(b||[]).map(x=>({id:x.id,full_name:x.full_name,name:x.name,private:x.private,default_branch:x.default_branch,html_url:x.html_url}))});}
  if(action==='github_attach'&&req.method==='POST'){const c=await providerConnection(projectId,user.id,'github');if(!c)return json(res,409,{error:'github_not_connected'});const b=body(req);if(typeof b.full_name!=='string'||!/^[^/]+\/[^/]+$/.test(b.full_name))return json(res,400,{error:'repository_required'});const token=openSealed(c.access_token_ciphertext);const r=await fetch(`https://api.github.com/repos/${b.full_name}`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});const rb=await r.json().catch(()=>({}));if(!r.ok)return json(res,502,{error:'github_repository_not_accessible'});const metadata={...(c.metadata||{}),repository:{full_name:rb.full_name,default_branch:rb.default_branch,html_url:rb.html_url}};await supabaseAdmin.from('developer_provider_connections').update({metadata,updated_at:new Date().toISOString()}).eq('id',c.id).eq('owner_user_id',user.id);return json(res,200,{repository:metadata.repository});}
  if(action==='vercel_projects'&&req.method==='GET'){const c=await providerConnection(projectId,user.id,'vercel');if(!c)return json(res,409,{error:'vercel_not_connected'});const token=openSealed(c.access_token_ciphertext);const r=await fetch('https://api.vercel.com/v9/projects?limit=100',{headers:{Authorization:`Bearer ${token}`}});const b=await r.json().catch(()=>({}));if(!r.ok)return json(res,502,{error:'vercel_projects_failed',details:b});return json(res,200,{projects:(b.projects||[]).map(x=>({id:x.id,name:x.name,framework:x.framework,latestDeployment:x.latestDeployment?.url||null}))});}
  if(action==='vercel_attach'&&req.method==='POST'){const c=await providerConnection(projectId,user.id,'vercel');if(!c)return json(res,409,{error:'vercel_not_connected'});const b=body(req);if(typeof b.vercel_project_id!=='string'||!b.vercel_project_id)return json(res,400,{error:'vercel_project_id_required'});const token=openSealed(c.access_token_ciphertext);const r=await fetch(`https://api.vercel.com/v9/projects/${encodeURIComponent(b.vercel_project_id)}`,{headers:{Authorization:`Bearer ${token}`}});const vb=await r.json().catch(()=>({}));if(!r.ok)return json(res,502,{error:'vercel_project_not_accessible'});const metadata={...(c.metadata||{}),vercel_project:{id:vb.id,name:vb.name,framework:vb.framework||null}};await supabaseAdmin.from('developer_provider_connections').update({metadata,updated_at:new Date().toISOString()}).eq('id',c.id).eq('owner_user_id',user.id);return json(res,200,{project:metadata.vercel_project});}
  return null;
}

export default async function handler(req,res){
  requestId(req,res);if(req.method==='OPTIONS')return json(res,204,{});
  const action=String(req.query?.action||'projects');const provider=String(req.query?.provider||'').toLowerCase();
  if(action==='oauth_callback')return oauthCallback(req,res,provider);
  const user=await resolveUser(req);if(!user)return json(res,401,{error:'authentication_required',request_id:req._merveilRequestId});
  try{
    const projectId=String(req.query?.project_id||'').trim();
    const providerResult=await providerData(req,res,user,action,projectId);if(providerResult)return providerResult;
    if(action==='projects'&&req.method==='GET'){const{data,error}=await supabaseAdmin.from('developer_projects').select('*').eq('owner_user_id',user.id).order('created_at',{ascending:false});if(error)return json(res,500,{error:error.message});return json(res,200,{projects:data||[]});}
    if(action==='projects'&&req.method==='POST'){const b=body(req);if(!nameOk(b.name))return json(res,400,{error:'invalid_project_name'});const runtime=['static','node','nextjs'].includes(b.runtime)?b.runtime:'static';const entry=typeof b.entry==='string'&&b.entry.trim()?b.entry.trim():'index.html';const{data,error}=await supabaseAdmin.from('developer_projects').insert({owner_user_id:user.id,name:b.name.trim(),slug:slug(b.name),tagline:b.tagline||'Merveil Developer Project',stage:'created',status_label:'Ready to build',momentum:0,twin:{runtime,entry,template:b.template||'blank'},meta:{capabilities:Array.isArray(b.capabilities)?b.capabilities:[]}}).select('*').single();if(error)return json(res,500,{error:error.message});const starter=runtime==='static'?[{path:'index.html',content:`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${b.name}</title></head><body><main><h1>${b.name}</h1><p>Built with Merveil Developer Platform.</p></main></body></html>`}]:[];if(starter.length)await supabaseAdmin.from('developer_project_files').insert(starter.map(f=>({...f,project_id:data.id,owner_user_id:user.id})));return json(res,201,{project:data,files:starter});}
    if(!projectId)return json(res,400,{error:'project_id_required'});
    const owner=await ownedProject(projectId,user.id);if(!owner)return json(res,404,{error:'project_not_found'});
    if(action==='files'&&req.method==='GET'){const{data,error}=await supabaseAdmin.from('developer_project_files').select('id,path,content,created_at,updated_at').eq('project_id',projectId).eq('owner_user_id',user.id).order('path');if(error)return json(res,500,{error:error.message});return json(res,200,{files:data||[]});}
    if(action==='files'&&['POST','PUT'].includes(req.method)){const b=body(req);if(typeof b.path!=='string'||!b.path.trim()||typeof b.content!=='string')return json(res,400,{error:'path_and_content_required'});const path=b.path.replace(/^\/+/, '');if(path.includes('..')||path.length>240)return json(res,400,{error:'invalid_path'});const{data,error}=await supabaseAdmin.from('developer_project_files').upsert({project_id:projectId,owner_user_id:user.id,path,content:b.content},{onConflict:'project_id,path'}).select('*').single();if(error)return json(res,500,{error:error.message});return json(res,200,{file:data});}
    if(action==='build'&&req.method==='POST'){const{data:files,error:fe}=await supabaseAdmin.from('developer_project_files').select('path,content').eq('project_id',projectId).eq('owner_user_id',user.id);if(fe)return json(res,500,{error:fe.message});const hasEntry=(files||[]).some(f=>f.path==='index.html');const status=hasEntry?'success':'failed';const logs=hasEntry?'Build validation passed: index.html found. Static project is deployable.':'Build validation failed: index.html is missing.';const{data,error}=await supabaseAdmin.from('developer_builds').insert({project_id:projectId,owner_user_id:user.id,status,logs,finished_at:new Date().toISOString()}).select('*').single();if(error)return json(res,500,{error:error.message});await supabaseAdmin.from('developer_projects').update({stage:status==='success'?'built':'build_failed',status_label:status==='success'?'Build passed':'Build failed',updated_at:new Date().toISOString()}).eq('id',projectId).eq('owner_user_id',user.id);return json(res,status==='success'?200:422,{build:data});}
    if(action==='deploy'&&req.method==='POST'){const token=process.env.VERCEL_TOKEN;if(!token)return json(res,503,{error:'vercel_deployment_not_configured'});const{data:files,error:fe}=await supabaseAdmin.from('developer_project_files').select('path,content').eq('project_id',projectId).eq('owner_user_id',user.id);if(fe)return json(res,500,{error:fe.message});if(!(files||[]).some(f=>f.path==='index.html'))return json(res,422,{error:'build_required_or_index_missing'});const created=await supabaseAdmin.from('developer_deployments').insert({project_id:projectId,owner_user_id:user.id,status:'building',provider:'vercel',logs:'Uploading project files to Vercel…'}).select('*').single();if(created.error)return json(res,500,{error:created.error.message});const vercelFiles=files.map(f=>({file:f.content,data:f.content,path:f.path}));const vr=await fetch('https://api.vercel.com/v13/deployments',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({name:`merveil-${owner.slug}-${projectId.slice(0,8)}`,project:`merveil-${owner.slug}-${projectId.slice(0,8)}`,files:vercelFiles,target:'production',teamId:process.env.VERCEL_TEAM_ID})});const vb=await vr.json().catch(()=>({}));if(!vr.ok){await supabaseAdmin.from('developer_deployments').update({status:'error',logs:JSON.stringify(vb)}).eq('id',created.data.id);return json(res,502,{error:'vercel_deployment_failed',details:vb});}const url=vb.url?`https://${vb.url}`:null;const state=vb.readyState==='READY'?'ready':'building';const{data:deployment}=await supabaseAdmin.from('developer_deployments').update({status:state,external_id:vb.id,url,logs:`Vercel deployment created: ${vb.id}`,ready_at:state==='ready'?new Date().toISOString():null}).eq('id',created.data.id).select('*').single();await supabaseAdmin.from('developer_projects').update({stage:'deployed',status_label:state==='ready'?'Deployed':'Deploying',updated_at:new Date().toISOString()}).eq('id',projectId).eq('owner_user_id',user.id);return json(res,200,{deployment,vercel:vb});}
    return json(res,404,{error:'not_found'});
  }catch(error){console.error('[developer-projects]',error);return json(res,500,{error:error.message||'internal_error'});}
}
