import React, { useEffect, useState } from "react";

const css = `
*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:#f5f7fb;color:#172033}button,input{font:inherit}.wrap{min-height:100vh}.top{height:68px;background:#fff;border-bottom:1px solid #e5e7eb;display:flex;align-items:center;justify-content:space-between;padding:0 22px}.brand{font-weight:900;letter-spacing:-.03em}.brand span{color:#2563eb}.main{max-width:1250px;margin:auto;padding:28px 20px}.hero,.card{background:#fff;border:1px solid #e5e7eb;border-radius:16px}.hero{padding:24px;display:flex;justify-content:space-between;gap:20px;align-items:center}.eyebrow{font-size:11px;font-weight:850;letter-spacing:.1em;color:#2563eb}.hero h1{font-size:30px;margin:8px 0}.muted{color:#667085;font-size:12px;line-height:1.55}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:14px 0}.card{padding:17px}.value{font-size:28px;font-weight:900;margin-top:10px}.label{font-size:12px;color:#667085;margin-top:3px}.evidence{font-size:10px;color:#98a2b3;margin-top:9px}.good{color:#16a34a}.warn{color:#d97706}.bad{color:#dc2626}.btn{border:1px solid #e5e7eb;background:#fff;border-radius:10px;padding:9px 12px;font-weight:750;cursor:pointer}.btn:hover{background:#f8fafc}.section{margin-top:20px}.section h2{font-size:20px;margin:0 0 5px}.rows{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.status{display:inline-flex;padding:5px 8px;border-radius:99px;background:#f8fafc;font-size:10px;font-weight:800}.notice{padding:11px 13px;border-radius:10px;background:#fff7ed;color:#9a3412;border:1px solid #fed7aa;font-size:12px;margin-bottom:12px}@media(max-width:800px){.grid,.rows{grid-template-columns:1fr 1fr}.hero{display:block}}@media(max-width:520px){.grid,.rows{grid-template-columns:1fr}}
`;

async function api(path, options={}){const r=await fetch(`/api/${path}`,{credentials:"include",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.message||`Request failed (${r.status})`);return d}
function Stat({label,value,evidence,tone}){return <div className="card"><div className="label">{label}</div><div className={`value ${tone||""}`}>{value===null||value===undefined?"—":value}</div><div className="evidence">Observed from: {evidence||"not available"}</div></div>}

export default function AdminTruthLayer(){
 const [admin,setAdmin]=useState(null),[data,setData]=useState(null),[apps,setApps]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const[o,a]=await Promise.all([api("admin-developer?action=overview"),api("admin-developer?action=applications")]);setData(o);setApps(a.applications||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{api("admin-auth?action=me").then(x=>setAdmin(x.admin)).catch(()=>setAdmin(null))},[]);useEffect(()=>{if(admin)load()},[admin]);
 const logout=async()=>{await api("admin-auth?action=logout",{method:"POST"}).catch(()=>{});setAdmin(null)};
 if(!admin&&!loading)return <><style>{css}</style><div className="wrap" style={{display:"grid",placeItems:"center",padding:20}}><div className="card" style={{width:"min(420px,100%)",padding:28}}><div className="brand">MERVEIL <span>AI</span></div><h1>Admin Control Center</h1><p className="muted">Private administrator access.</p><Login onDone={setAdmin}/></div></div></>;
 if(loading)return <><style>{css}</style><div style={{padding:40,textAlign:"center"}}>Loading verified production metrics…</div></>;
 const d=data||{};const e=d.evidence||{};const freshness=d.generatedAt?new Date(d.generatedAt).toLocaleString():"unknown";
 return <><style>{css}</style><div className="wrap"><header className="top"><div className="brand">MERVEIL <span>AI</span> <small style={{fontWeight:600,color:"#667085"}}>Control Center</small></div><div style={{display:"flex",gap:10,alignItems:"center"}}><span className="muted">{admin?.name||admin?.email}</span><button className="btn" onClick={logout}>Sign out</button></div></header><main className="main">
  <div className="hero"><div><div className="eyebrow">PRODUCTION EVIDENCE</div><h1>Admin reports what Merveil can prove.</h1><p className="muted">No synthetic totals, demo activity or optimistic status labels. Every metric below is read from a production database record.</p></div><button className="btn" onClick={load}>↻ Refresh</button></div>
  {error&&<div className="notice" style={{marginTop:12}}>{error}</div>}
  <div className="grid"><Stat label="Citizens" value={d.citizens} evidence={e.citizens}/><Stat label="Platform events · 24h" value={d.activity24h} evidence={e.activity24h}/><Stat label="Security events · 24h" value={d.securityEvents24h?.total} evidence={e.securityEvents24h}/><Stat label="Active sessions · 30m" value={d.activeSessions} evidence={e.activeSessions}/></div>
  <div className="grid"><Stat label="Calls · 24h" value={d.calls24h} evidence={e.calls24h}/><Stat label="Open reports" value={d.reportsOpen} evidence={e.reports}/><Stat label="All reports" value={d.reportsTotal} evidence={e.reports}/><Stat label="Developer applications" value={d.applications} evidence={e.developerApplications}/></div>
  <section className="section"><h2>Security evidence</h2><p className="muted">These are observed security records, not a fabricated security score.</p><div className="rows"><Stat label="Critical · 24h" value={d.securityEvents24h?.critical} evidence={e.securityEvents24h} tone={(d.securityEvents24h?.critical||0)>0?"bad":"good"}/><Stat label="High · 24h" value={d.securityEvents24h?.high} evidence={e.securityEvents24h} tone={(d.securityEvents24h?.high||0)>0?"warn":"good"}/></div></section>
  <section className="section"><h2>Developer evidence</h2><p className="muted">No developer activity is displayed unless the corresponding production table contains it.</p><div className="rows"><div className="card"><b>Applications</b><div className="muted" style={{marginTop:7}}>{apps.length?`${apps.length} applications returned from api_applications.`:"No applications currently recorded."}</div></div><Stat label="API usage · 24h" value={d.usage24h} evidence={e.apiUsage24h}/></div></section>
  <section className="section"><div className="card"><b>Report integrity</b><div className="muted" style={{marginTop:7}}>Generated {freshness}. Null means the metric could not be measured. The dashboard never substitutes “Live”, invented counts, or hard-coded product totals.</div></div></section>
 </main></div></>;
}
function Login({onDone}){const[e,setE]=useState(""),[p,setP]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);const submit=async()=>{if(!e||!p)return setErr("Enter administrator credentials.");setBusy(true);try{const d=await api("admin-auth?action=login",{method:"POST",body:JSON.stringify({email:e,password:p})});onDone(d.admin)}catch(x){setErr(x.message)}finally{setBusy(false)}};return <div><input value={e} onChange={x=>setE(x.target.value)} placeholder="Administrator email" type="email" style={{width:"100%",padding:11,border:"1px solid #e5e7eb",borderRadius:9}}/><input value={p} onChange={x=>setP(x.target.value)} onKeyDown={x=>x.key==="Enter"&&submit()} placeholder="Password" type="password" style={{width:"100%",padding:11,border:"1px solid #e5e7eb",borderRadius:9,marginTop:9}}/>{err&&<div className="notice" style={{marginTop:9}}>{err}</div>}<button className="btn" style={{width:"100%",marginTop:12}} onClick={submit} disabled={busy}>{busy?"Signing in…":"Enter Control Center"}</button></div>}
