import React, { useMemo, useState } from "react";

const LAYERS = [
  { id: "intelligence", name: "PULSE Intelligence", role: "Understands and reasons about the physical world", status: "CODE PRESENT · RUNTIME UNVERIFIED", color: "#7c8cff", features: ["Multimodal intelligence jobs", "Document / knowledge pipeline", "Domain analysis", "Anomaly & diagnostic reasoning", "Prediction and planning", "Federated intelligence foundation"], evidence: "machine-connect/intelligence + core intelligence/graph integration" },
  { id: "dna", name: "Machine DNA", role: "Defines what a machine is, can do, and how it is configured", status: "CORE MODEL PRESENT · UI NEEDS EXPOSURE", color: "#38d9c5", features: ["Machine identity", "Capabilities", "Configuration", "Health profile", "Digital-twin state", "Machine lifecycle"], evidence: "machine domain + capability model + twin runtime" },
  { id: "shield", name: "PULSE Shield", role: "Safety, authorization, policy and controlled execution boundary", status: "CORE PRESENT · RUNTIME UNVERIFIED", color: "#f5b86a", features: ["Authorization scopes", "Policy evaluation", "Safety decision", "Approval gates", "Emergency stop", "Audit / security events"], evidence: "core safety + security + audit modules" },
  { id: "procedure", name: "Procedure Execution", role: "Turns approved procedures into controlled, observable workflows", status: "CORE PRESENT · RUNTIME UNVERIFIED", color: "#b18cff", features: ["Procedure definitions", "Preconditions", "Workflow execution", "Retries / reliability", "Closed-loop actions", "Evidence"], evidence: "core workflow + operations + execution worker" },
  { id: "machine-connect", name: "Machine Connect", role: "The physical connectivity and control plane", status: "FRONTEND PRESENT · CORE API NOT CONNECTED", color: "#5ea8ff", features: ["Machine registry", "MQTT / protocol adapters", "Telemetry", "Commands", "Acknowledgements", "CHRYSALIS modernization"], evidence: "MachineConnectPlatform + NestJS core + adapters" },
  { id: "fleet", name: "Fleet", role: "Coordinates many machines, sites and operational workloads", status: "CORE PRESENT · NO LIVE FLEET DATA", color: "#6ee7a8", features: ["Fleet registry", "Sites / organizations", "Fleet intelligence", "Rollouts", "Operational scheduling", "Remediation"], evidence: "core fleet + fleet-intelligence modules" },
  { id: "digital-twin", name: "Digital Twin", role: "Maintains machine state and historical operational context", status: "CORE PRESENT · NO LIVE TWIN DATA", color: "#59c7ff", features: ["Current state", "Historical snapshots", "Telemetry reconciliation", "Events", "What-if / twin simulation"], evidence: "core twin + digital-twin + advanced twin simulation" },
  { id: "edge", name: "PULSE Edge", role: "Local / degraded / air-gapped intelligence and operations", status: "LOCAL RUNTIME PRESENT · NOT CLOUD-LIVE", color: "#d6e27a", features: ["Offline queue", "Local database", "Local safety governor", "Store-and-forward sync", "Edge agent", "Air-gapped mode"], evidence: "machine-connect/edge + machine-connect/offline" },
  { id: "graph", name: "Physical Knowledge Graph", role: "Connects machines, entities, documents and relationships for reasoning", status: "CORE PRESENT · RUNTIME UNVERIFIED", color: "#e88cff", features: ["Entities", "Relationships", "Documents", "PageRank", "Communities", "Shortest-path analysis"], evidence: "core graph module + document processor + analytics" },
  { id: "developer", name: "PULSE Developer API / SDK", role: "Makes PULSE capabilities programmable and integrable", status: "SDK / API FOUNDATION PRESENT", color: "#ff8fa3", features: ["API keys", "Scoped access", "Machine APIs", "Telemetry APIs", "Command APIs", "Merveil SDK packages"], evidence: "packages/merveil-sdk + packages/merveil-js + core API-key/security modules" },
  { id: "synapse", name: "SYNAPSE", role: "Visual operating surface that brings PULSE layers together", status: "ARCHITECTURE TARGET · UI INTEGRATION NEEDED", color: "#ffcb6b", features: ["Visual machine workspace", "Relationships", "Intelligence", "Diagnostics", "Operations"], evidence: "PULSE architecture; no dedicated production SYNAPSE workspace found in current src tree" },
  { id: "find", name: "PULSE FIND", role: "Authorized finding and matching services across physical-world entities", status: "ARCHITECTURE TARGET · NOT IMPLEMENTED IN CURRENT UI", color: "#9aa7ff", features: ["People finding", "Pet finding", "Vehicle finding", "General finding", "Matching", "Authorized evidence"], evidence: "No dedicated FIND registration / embedding / search UI found in current tree" },
];

function StatusPill({ status, color }) { return <span className="pulse-status" style={{ "--pulse-accent": color }}>{status}</span>; }

function LayerCard({ item, selected, onSelect }) {
  return <button className={`pulse-layer-card ${item.id === selected ? "selected" : ""}`} onClick={() => onSelect(item.id)} style={{ "--layer-accent": item.color }}>
    <div className="pulse-card-top"><span className="pulse-card-name">{item.name}</span><span className="pulse-card-dot" /></div>
    <StatusPill status={item.status} color={item.color}/>
    <div className="pulse-card-role">{item.role}</div>
    <div className="pulse-card-count">{item.features.length} feature areas</div>
  </button>;
}

export default function PULSEOwnerWorkspace({ onBack }) {
  const [selected, setSelected] = useState("intelligence");
  const [search, setSearch] = useState("");
  const [showAll, setShowAll] = useState(true);
  const [testMessage, setTestMessage] = useState("");
  const layer = useMemo(() => LAYERS.find((item) => item.id === selected) || LAYERS[0], [selected]);
  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return LAYERS;
    return LAYERS.filter((item) => `${item.name} ${item.role} ${item.features.join(" ")}`.toLowerCase().includes(q));
  }, [search]);

  const runOwnerCheck = (item, feature) => {
    setTestMessage(`${item.name} · ${feature}: no executable production endpoint is registered in this workspace yet. Nothing simulated or fabricated.`);
    if (item.id === "machine-connect") {
      setTestMessage("Opening the existing Machine Connect workspace. Its controls remain separate from PULSE Intelligence, DNA, Shield and the other PULSE layers.");
      window.location.assign("/machine-connect");
    }
  };

  return <main className="pulse-owner">
    <style>{`
      .pulse-owner{min-height:100vh;background:#05070c;color:#eef2f7;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:26px;box-sizing:border-box}.pulse-shell{width:min(1500px,100%);margin:0 auto}
      .pulse-top{display:flex;align-items:center;justify-content:space-between;gap:20px;border-bottom:1px solid rgba(255,255,255,.07);padding:8px 0 20px}.pulse-brand{display:flex;align-items:center;gap:12px}.pulse-mark{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;border:1px solid rgba(124,140,255,.35);background:linear-gradient(145deg,rgba(124,140,255,.2),rgba(56,217,197,.08));font-weight:900}.pulse-brand small{display:block;color:#69758a;font-size:10px;letter-spacing:.16em;text-transform:uppercase;margin-top:2px}.pulse-back{background:transparent;border:1px solid rgba(255,255,255,.1);color:#aab4c3;padding:9px 13px;border-radius:10px;cursor:pointer}.pulse-back:hover{border-color:rgba(255,255,255,.22);color:#fff}
      .pulse-hero{padding:44px 0 30px;display:flex;justify-content:space-between;gap:30px;align-items:flex-end}.pulse-kicker{font-size:11px;letter-spacing:.2em;text-transform:uppercase;color:#8fa4ff;font-weight:800}.pulse-title{font-size:clamp(42px,6vw,78px);line-height:.95;letter-spacing:-.055em;margin:10px 0 16px}.pulse-copy{max-width:860px;color:#8995a7;line-height:1.65;font-size:15px}.pulse-hero-note{border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.025);border-radius:16px;padding:16px 18px;min-width:250px}.pulse-hero-note b{display:block;font-size:12px}.pulse-hero-note span{display:block;margin-top:7px;color:#748094;font-size:11px;line-height:1.5}
      .pulse-boundary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:0 0 20px}.pulse-boundary-item{border:1px solid rgba(255,255,255,.07);border-radius:14px;padding:15px;background:#090d15}.pulse-boundary-item b{font-size:11px}.pulse-boundary-item span{display:block;color:#707c90;font-size:11px;line-height:1.5;margin-top:6px}
      .pulse-toolbar{display:flex;gap:10px;align-items:center;margin:4px 0 18px}.pulse-search{flex:1;max-width:500px;background:#0a0e16;border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:11px 13px;color:#fff;outline:none}.pulse-toggle{border:1px solid rgba(255,255,255,.1);background:#0a0e16;color:#9ca8b8;border-radius:10px;padding:10px 13px;cursor:pointer}
      .pulse-layer-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:18px}.pulse-layer-card{width:100%;text-align:left;background:#090d15;border:1px solid rgba(255,255,255,.07);border-radius:15px;color:#a2adbd;padding:15px;cursor:pointer;min-height:145px}.pulse-layer-card:hover{border-color:rgba(255,255,255,.18)}.pulse-layer-card.selected{border-color:color-mix(in srgb,var(--layer-accent) 35%,rgba(255,255,255,.08));background:color-mix(in srgb,var(--layer-accent) 5%,#090d15)}.pulse-card-top{display:flex;justify-content:space-between;align-items:center;gap:10px}.pulse-card-name{font-size:13px;font-weight:850;color:#edf1f7}.pulse-card-dot{width:7px;height:7px;border-radius:50%;background:var(--layer-accent);box-shadow:0 0 13px color-mix(in srgb,var(--layer-accent) 50%,transparent)}.pulse-card-role{font-size:11px;line-height:1.45;color:#788499;margin-top:10px}.pulse-card-count{font-size:10px;color:#566275;margin-top:12px}
      .pulse-layout{display:grid;grid-template-columns:330px minmax(0,1fr);gap:16px}.pulse-nav,.pulse-detail{border:1px solid rgba(255,255,255,.08);background:rgba(10,14,22,.86);border-radius:18px}.pulse-nav{padding:10px;align-self:start;position:sticky;top:16px}.pulse-nav-item{width:100%;text-align:left;background:transparent;border:1px solid transparent;color:#a2adbd;padding:13px 12px;border-radius:12px;cursor:pointer;margin-bottom:4px}.pulse-nav-item:hover{background:rgba(255,255,255,.03);color:#fff}.pulse-nav-item.active{background:rgba(124,140,255,.09);border-color:rgba(124,140,255,.2);color:#fff}.pulse-nav-name{font-weight:800;font-size:13px}.pulse-nav-role{font-size:10px;color:#667287;margin-top:5px;line-height:1.35}.pulse-nav-item.active .pulse-nav-role{color:#8997b1}
      .pulse-detail{padding:26px}.pulse-detail-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;border-bottom:1px solid rgba(255,255,255,.07);padding-bottom:22px}.pulse-detail-title{font-size:28px;font-weight:850;letter-spacing:-.03em;margin:0 0 7px}.pulse-detail-role{color:#7e899b;font-size:13px}.pulse-status{display:inline-flex;align-items:center;white-space:nowrap;border:1px solid color-mix(in srgb,var(--pulse-accent) 28%,transparent);background:color-mix(in srgb,var(--pulse-accent) 8%,transparent);color:var(--pulse-accent);font-size:9px;font-weight:900;letter-spacing:.11em;padding:8px 10px;border-radius:999px}.pulse-section{padding:22px 0;border-bottom:1px solid rgba(255,255,255,.07)}.pulse-section:last-child{border-bottom:0}.pulse-section h3{font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:#667287;margin:0 0 13px}.pulse-features{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.pulse-feature{padding:12px;border:1px solid rgba(255,255,255,.07);border-radius:11px;color:#aab4c2;font-size:12px;background:rgba(255,255,255,.018)}.pulse-evidence{font-family:"SFMono-Regular",Consolas,monospace;color:#8490a3;font-size:11px;line-height:1.6}.pulse-tests{display:flex;flex-wrap:wrap;gap:8px}.pulse-test{border:1px solid rgba(255,255,255,.1);background:#0b1019;color:#b7c0cd;border-radius:9px;padding:9px 11px;font-size:11px;cursor:pointer}.pulse-test:hover{border-color:rgba(255,255,255,.22);color:#fff}.pulse-test-note{margin-top:12px;border:1px dashed rgba(255,255,255,.1);border-radius:10px;padding:11px;color:#778397;font-size:11px;line-height:1.5}.pulse-divider{display:flex;gap:8px;align-items:center;margin-top:15px;color:#5f6a7b;font-size:10px}.pulse-dot{width:6px;height:6px;border-radius:50%;background:#f5b86a;box-shadow:0 0 12px rgba(245,184,106,.4)}
      @media(max-width:1150px){.pulse-layer-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.pulse-boundary{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:900px){.pulse-hero{flex-direction:column;align-items:flex-start}.pulse-layout{grid-template-columns:1fr}.pulse-nav{position:static}.pulse-detail-head{flex-direction:column}.pulse-features{grid-template-columns:1fr}.pulse-layer-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.pulse-owner{padding:18px}.pulse-layer-grid,.pulse-boundary{grid-template-columns:1fr}.pulse-title{font-size:50px}}
    `}</style>
    <div className="pulse-shell">
      <header className="pulse-top"><div className="pulse-brand"><div className="pulse-mark">P</div><div><strong>PULSE</strong><small>Private owner workspace · IVONIX</small></div></div>{onBack && <button className="pulse-back" onClick={onBack}>← Merveil entry</button>}</header>
      <section className="pulse-hero"><div><div className="pulse-kicker">Physical intelligence infrastructure</div><h1 className="pulse-title">PULSE is the intelligence layer.<br/>Machine Connect is one component.</h1><p className="pulse-copy">This workspace makes the boundaries explicit. Intelligence reasons. Machine DNA defines the machine. Shield governs safety. Procedure Execution controls workflows. Machine Connect handles connectivity. Fleet handles scale. Digital Twin maintains state. Edge handles disconnected operation. SYNAPSE is the visual operating surface.</p></div><div className="pulse-hero-note"><b>Owner test mode</b><span>No simulated production machine data is created here. Source code, backend presence and live connectivity are tracked separately.</span></div></section>
      <section className="pulse-boundary"><div className="pulse-boundary-item"><b>Understand</b><span>PULSE Intelligence turns physical-world signals into analysis, diagnosis, prediction and planning.</span></div><div className="pulse-boundary-item"><b>Define</b><span>Machine DNA describes identity, capabilities, configuration, health and twin context.</span></div><div className="pulse-boundary-item"><b>Govern</b><span>PULSE Shield decides whether an action is authorized and safe before execution.</span></div><div className="pulse-boundary-item"><b>Connect</b><span>Machine Connect is the transport/control plane. It is not the entire PULSE intelligence stack.</span></div></section>
      <div className="pulse-toolbar"><input className="pulse-search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search PULSE layers or capabilities…"/><button className="pulse-toggle" onClick={() => setShowAll((value) => !value)}>{showAll ? "Focused layer" : "Layer overview"}</button></div>
      {showAll && <section className="pulse-layer-grid">{filtered.map((item) => <LayerCard key={item.id} item={item} selected={selected} onSelect={setSelected}/>)}</section>}
      <section className="pulse-layout">
        <nav className="pulse-nav" aria-label="PULSE layers">{filtered.map((item) => <button key={item.id} className={`pulse-nav-item ${item.id === selected ? "active" : ""}`} onClick={() => setSelected(item.id)}><div className="pulse-nav-name">{item.name}</div><div className="pulse-nav-role">{item.role}</div></button>)}</nav>
        <article className="pulse-detail"><div className="pulse-detail-head"><div><h2 className="pulse-detail-title">{layer.name}</h2><div className="pulse-detail-role">{layer.role}</div></div><StatusPill status={layer.status} color={layer.color}/></div>
          <div className="pulse-section"><h3>What this layer owns</h3><div className="pulse-features">{layer.features.map((feature) => <div className="pulse-feature" key={feature}>{feature}</div>)}</div></div>
          <div className="pulse-section"><h3>Implementation evidence</h3><div className="pulse-evidence">{layer.evidence}</div><div className="pulse-divider"><span className="pulse-dot"/> Code presence does not equal live production connectivity.</div></div>
          <div className="pulse-section"><h3>Owner test surface</h3><div className="pulse-tests">{layer.features.map((feature) => <button key={feature} className="pulse-test" onClick={() => runOwnerCheck(layer, feature)}>Inspect {feature}</button>)}</div><div className="pulse-test-note">{testMessage || "Tests are evidence-first. If a real endpoint/runtime is not wired, this workspace reports that fact instead of generating a fake success."}</div></div>
        </article>
      </section>
    </div>
  </main>;
}
