import { createClient } from '@supabase/supabase-js';
export function supabaseAdmin(){const url=process.env.SUPABASE_URL||`https://${process.env.SUPABASE_PROJECT_REF||'dixfybqlepticyudikuz'}.supabase.co`;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
export async function requireUser(req,db){const h=req.headers.authorization||'';const token=h.startsWith('Bearer ')?h.slice(7):'';if(!token){const e=new Error('Missing bearer token');e.status=401;throw e;}const {data,error}=await db.auth.getUser(token);if(error||!data.user){const e=new Error('Invalid session');e.status=401;throw e;}return data.user;}
export function json(res,status,body){res.status(status).setHeader('Content-Type','application/json');return res.end(JSON.stringify(body));}
export function createOpportunities(context={}){const country=context.country||context.countryCode||'your country',city=context.city||context.region||'your local area',skills=Array.isArray(context.skills)?context.skills:[],interests=Array.isArray(context.interests)?context.interests:[],skillText=skills.length?skills.join(', '):'your existing skills',interestText=interests.length?interests.join(', '):'your interests';return[
{id:'local-service',kind:'local_service',title:`Build a ${city} service around ${skillText}`,one_liner:'Turn an existing skill into a service you can test locally.',why_you:`Your stated skills: ${skillText}.`,why_now:'Local delivery can be tested without a large initial product.',effort:'low',first_steps:[`Identify 3 recurring needs in ${city}`,'Offer one narrow service to 5 potential customers','Record what people actually pay or request'],risks:['Demand may be weaker than expected','Operational capacity may limit growth'],monetization:['direct service fees','retainers'],confidence:.55,evidence:{type:'hypothesis',basis:'user_context'},create_prompt:`Create a launch kit for a ${city} service using ${skillText}.`},
{id:'skill-digital',kind:'skill_monetization',title:`Turn ${skillText} into a digital offer`,one_liner:'Package a skill into a repeatable digital product or service.',why_you:'Uses skills the user reported rather than invented resources.',why_now:'Digital delivery can expand beyond one location once validated.',effort:'medium',first_steps:['Choose one narrow customer problem','Create one sample outcome','Test with 10 targeted prospects'],risks:['Crowded market','Need for consistent delivery quality'],monetization:['digital products','consulting','subscriptions'],confidence:.50,evidence:{type:'hypothesis',basis:'user_context'},create_prompt:`Create the first digital product and launch assets for ${skillText}.`},
{id:'creator',kind:'creative',title:`Build a creator identity around ${interestText}`,one_liner:'Turn an interest into repeatable content and a recognizable identity.',why_you:'Your interests provide a starting creative direction.',why_now:'Short-form distribution makes small experiments inexpensive.',effort:'medium',first_steps:[`Define one audience in ${country}`,'Create 10 pieces around one repeatable format','Measure real audience response before scaling'],risks:['Audience growth is uncertain','Consistency required'],monetization:['sponsorships','digital products','services'],confidence:.45,evidence:{type:'hypothesis',basis:'user_context'},create_prompt:`Create a 10-piece creator launch package around ${interestText} for ${country}.`},
{id:'problem-product',kind:'problem_solution',title:'Turn a real problem into a product',one_liner:'Start with a problem you personally understand and test a small solution.',why_you:'Personal experience can reduce discovery cost without assuming market demand.',why_now:'A manual service can validate the workflow before software is built.',effort:'high',first_steps:['Write the exact problem and affected user','Solve it manually for 3 people','Identify the repeatable part worth building'],risks:['Problem may not be painful enough','Automation may be premature'],monetization:['service','software subscription'],confidence:.40,evidence:{type:'hypothesis',basis:'user_context'},create_prompt:'Create a validation prototype for the stated problem.'}];}
export function creationPlanFor(raw,primary='text'){const objective=String(raw||'').trim();return{objective,primaryModality:primary,steps:[{key:'understand',capability:'text.generate',modality:'text',produces:['spec']},{key:'script',capability:'text.generate',modality:'text',produces:['script'],dependsOn:['understand']},{key:'visual',capability:'image.generate',modality:'image',produces:['image'],dependsOn:['script']},{key:'video',capability:'video.generate',modality:'video',produces:['video_clip'],dependsOn:['script','visual']},{key:'voice',capability:'voice.generate',modality:'voice',produces:['voiceover'],dependsOn:['script']},{key:'music',capability:'music.generate',modality:'audio',produces:['music'],dependsOn:['script']},{key:'assembly',capability:'video.assemble',modality:'assembly',produces:['composition'],dependsOn:['video','voice','music']}]};}
