import { createClient } from '@supabase/supabase-js';
import { getSession, sendJson } from '../lib/supabaseServer.js';

const SUPABASE_URL='https://dixfybqlepticyudikuz.supabase.co';
function db(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_ROLE;if(!key)throw new Error('Missing SUPABASE_SERVICE_ROLE_KEY');return createClient(SUPABASE_URL,key,{auth:{autoRefreshToken:false,persistSession:false}})}
async function uid(req,res){const s=await getSession(req,res).catch(()=>({user:null,jwtSub:null}));return s?.user?.id||s?.jwtSub||null}
function cleanName(v){return String(v??'').replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim().slice(0,120)}
function slugify(v){return String(v||'project').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'project'}
async function owned(database,id,owner){const{data,error}=await database.from('developer_projects').select('id,name,slug,tagline,stage,status_label,momentum,created_at,updated_at').eq('id',id).eq('owner_user_id',owner).maybeSingle();if(error)throw error;return data}
async function uniqueSlug(database,base,owner,ignoreId=null){let slug=slugify(base),candidate=slug;for(let n=2;n<=20;n++){let q=database.from('developer_projects').select('id').eq('owner_user_id',owner).eq('slug',candidate).limit(1);if(ignoreId)q=q.neq('id',ignoreId);const{data,error}=await q;if(error)throw error;if(!data?.length)return candidate;candidate=`${slug}-${n}`}throw new Error('Could not create a unique project slug')}
export default async function handler(req,res){const owner_user_id=await uid(req,res);if(!owner_user_id)return sendJson(res,401,{error:'Sign in required',code:'AUTH_REQUIRED'});try{const database=db();if(req.method==='GET'){const{data,error}=await database.from('developer_projects').select('id,name,slug,tagline,stage,status_label,momentum,created_at,updated_at').eq('owner_user_id',owner_user_id).order('updated_at',{ascending:false}).limit(50);if(error)throw error;return sendJson(res,200,{ok:true,projects:data||[]})}if(req.method!=='POST')return sendJson(res,405,{error:'Method not allowed'});let body;try{body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{})}catch{return sendJson(res,400,{error:'Invalid JSON',code:'INVALID_JSON'})}const action=body.action||'select';if(action==='select'){if(!body.projectId)return sendJson(res,400,{error:'projectId required'});const project=await owned(database,body.projectId,owner_user_id);if(!project)return sendJson(res,404,{error:'Project not found'});return sendJson(res,200,{ok:true,project,activeProjectId:project.id})}if(action==='create'){const name=cleanName(body.name||'Untitled project');if(!name)return sendJson(res,400,{error:'Project name is required'});const slug=await uniqueSlug(database,body.slug||name,owner_user_id);const{data,error}=await database.from('developer_projects').insert({owner_user_id,name,slug,tagline:String(body.tagline||'').replace(/[\u0000-\u001F\u007F]/g,' ').slice(0,240),stage:'build',status_label:'Ready',momentum:0}).select('id,name,slug,tagline,stage,status_label,momentum,created_at,updated_at').single();if(error)throw error;return sendJson(res,201,{ok:true,project:data,activeProjectId:data.id})}if(action==='rename'){if(!body.projectId)return sendJson(res,400,{error:'projectId required'});const name=cleanName(body.name);if(!name)return sendJson(res,400,{error:'Project name is required'});const project=await owned(database,body.projectId,owner_user_id);if(!project)return sendJson(res,404,{error:'Project not found'});const slug=await uniqueSlug(database,body.slug||name,owner_user_id,project.id);const{data,error}=await database.from('developer_projects').update({name,slug}).eq('id',project.id).eq('owner_user_id',owner_user_id).select('id,name,slug,tagline,stage,status_label,momentum,created_at,updated_at').single();if(error)throw error;return sendJson(res,200,{ok:true,project:data,activeProjectId:data.id})}return sendJson(res,400,{error:'Unknown action',supported:['select','create','rename']})}catch(e){return sendJson(res,500,{error:e?.message||'Developer project failed'})}}
